version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/auth-service"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/order-service"
    schedule:
      interval: "daily"
